
["Change Spawn Entities - Global"]
	#For each tick.This affects the Stalker Villager and entities that disappear around the player. Be careful what you modify. If you are not sure, do not change the numbers.
	"Change Entities Minimum Ticks Spawn" = 36000.0
	#For each tick. This affects the Stalker Villager and entities that disappear around the player. Be careful what you modify. If you are not sure, do not change the numbers.
	"Change Entities Maximum Ticks Spawn" = 108000.0
	#It is recommended to leave the probability at 1 by default.
	"Min Despawn Probability" = 1.0
	#Changes the spawn probability of the mobs
	"Max Despawn Probability" = 3.0
	"Enable Villager Stalker?" = true

["Change Villager Stalker Spawn"]
	#Probability of Villager Stalker spawning with respect to global time The default values have been tested. It is recommended to leave them like this 
	"Villager Stalker Minimum Spawn" = 1.0
	#Probability of Villager Stalker spawning with respect to global time The default values have been tested. It is recommended to leave them like this 
	"Villager Stalker Maximum Spawn" = 4.0
	#For each tick.
	"Villager Stalker Minimum Ticks Despawn" = 400.0
	#For each tick.
	"Villager Stalker  Maximum Ticks Despawn" = 1000.0

["Chicken Spawn Probablity"]
	#If the chicken is attacked, then there is a chance that the hostile entity will spawn.
	"Chicken Minimum Spawn" = 1.0
	#If the chicken is attacked, then there is a chance that the hostile entity will spawn.
	"Chicken Maximum Spawn" = 30.0
	#For each tick.The default values ​​have been tested. It is recommended to leave them like this
	"Chicken Minimum Ticks Despawn" = 600.0
	#For each tick.The default values ​​have been tested. It is recommended to leave them like this
	"Chicken Maximum Ticks Despawn" = 900.0
	"Enable Chicken Spawn?" = true

["Change Global Spawn"]
	#For each tick.This affects the Flying villagers, Cow and Chicken and Invisible Entity. Be careful what you modify. If you are not sure, do not change the numbers.
	"Minimum Ticks Spawn" = 40000.0
	#For each tick.This affects the Flying villagers, Cow and Chicken and Invisible Entity. Be careful what you modify. If you are not sure, do not change the numbers.
	"Maximum Ticks Spawn" = 108000.0

["Flying Villagers Spawn"]
	#Random Min Probability Spawn
	"Flying Villagers Minimum Spawn" = 1.0
	#Random Max Probability Spawn
	"Flying Villagers Maximum Spawn" = 3.0
	#For each tick!
	"Flying Villagers Minimum Ticks Despawn" = 1000.0
	#For each tick!
	"Flying Villagers Maximum Ticks Despawn" = 1600.0

["Stalker Cow and Chicken Spawn"]
	#Random Min Probability Spawn
	"Stalker Cow Minimum Spawn" = 1.0
	#Random Max Probability Spawn
	"Stalker Cow Maximum Spawn" = 4.0
	#Random Min Probability Spawn
	"Stalker Chicken Minimum Spawn" = 1.0
	#Random Max Probability Spawn
	"Stalker Chicken Maximum Spawn" = 4.0
	"Enable Chicken and Cow Spawn?" = true

["Villagers Rain"]
	#For each tick!
	"Rain Villagers Minimum Ticks Spawn" = 1.0
	#For each tick!
	"Rain Villagers Maximum Ticks Spawn" = 20000.0

["Night Global"]
	#It is necessary to leave this option activated to edit those that are related to this
	"Enable Night randomly?" = true
	#Minimum time for nightfall (ticks)
	"Randomly Night Min Ticks" = 6000.0
	#Maximum time for nightfall (ticks)
	"Randomly Night Max Ticks" = 48000.0

["Spawn Smile Block"]
	#Do you want the Smile Block to spawn when you start the world for the first time?
	"Enable Smile Block Spawn" = true

["Torches Despawn"]
	#It is necessary to leave it enabled if you will change other values
	"Enable Torches Randomly Despawn?" = true
	#The higher the number, the faster it will despawn.
	"Random Torch Despawn Probability" = 0.16
	#Establishes the minimum probability in ticks that it can despawn (ticks)
	"Start despawn from (ticks)" = 1200.0
	#Establishes the maximum probability in ticks that it can despawn (ticks)
	"End spawn chance from (ticks)" = 6000.0

["Sounds Global"]
	#For each tick!
	"Random Sounds Min Probability" = 1.0
	#For each tick!
	"Random Sounds Max Probability" = 180.0
	#It is necessary to leave it enabled if you will change other values
	"Enable Mod Sounds?" = true
	#If you have the In Your World mod installed, you need to disable this.. This sound pack will be heard when the player is not inside a cave, structure or underground. The higher the number, the more frequent it will be for the player
	"Sounds 1: How often will the sounds be heard? " = 0.004
	#This sound pack will be heard when the player is inside a cave, structure, or underground. The higher the number, the more frequent it will be for the player.
	"Sounds 2: How often will the sounds be heard? " = 0.004
	#This sound pack will be heard when the player is inside a cave, structure, or underground. The higher the number, the more frequent it will be for the player.
	"Sounds 3: How often will the sounds be heard? " = 0.007
	"Enable Entities Spawn in Villages?" = true

["Player goes to bed"]
	#It is necessary to leave it enabled if you will change other values
	"Activate Spawn Chicken?" = true
	#Establishes the maximum probability that the Chicken can spawn when player goes to bed
	"Max Chicken Bed Spawn Rate" = 300.0
	#Establishes the minimum probability that the Chicken can spawn when player goes to bed
	"Min Chicken Bed Spawn Rate" = 1.0

["Spawn Eye Entity Global"]
	#You need to keep this enabled for the other settings in this category to work.
	"Spawn Eye?" = true
	#Establishes the minimum probability in ticks that it can spawn
	"Spawn Eye Min Probability" = 24000.0
	#Establishes the maximum probability in ticks that it can spawn
	"Spawn Eye Max Probability" = 64000.0
	#The structure has a minimum spawn probability of 1. Now enter the maximum amount (1≠1)
	"Change Max Probability Spawn " = 4.0
	#Change Eye Entity Despawn (ticks)
	"Change Despawn" = 150.0
	#If the Eye Entity spawns, it will also spawn structure (test)
	"Spawn Eye Structure" = true

["Door and Glass"]
	#If the player opens the door then the entity has a probability of entering
	"Enable if Player Open the Door?" = true
	#If the player places a glass block, the entity has a chance to break it
	"Enable if put a glass block" = true
	#When the player opens the door, there is a chance that the entity can open it. The lower the number, the more likely it is.
	"Enable Entity Open the Door?" = 80.0
	#When the player closes the door, there is a chance that the entity can close it as well. The lower the number, the more likely it is.
	"Enable Entity Close the Door?" = 80.0
	#When the player places a block,  there is a chance that the entity will break it. The lower the number, the higher the probability of it occurring.
	"Enable Entity can break glass?" = 55.0
	#When the player is near a glass block, there is a chance that the entity will break it
	"Probability Break Glass Block when player is nearby" = true
	#When the player is near a glass block, there is a chance that the entity will break it. The lower the number, the more likely it is to occur.
	"Probability Entity break glass around the player" = 3.0
	#Distance number to break glass blocks. The smaller the number, the greater the distance.
	"Break Glass Blocks Distance" = -10.0
	#Minimum probability in ticks to break glass blocks near the player
	"Min Probability Break Glass Block" = 24000.0
	#Maximum chance in ticks to break glass blocks near the player
	"Max Probability Break Glass Block" = 64000.0

[Balloon]
	#Probability that the balloon will explode. If it explodes, other events will happen later. The higher the number, the rarer it will be.
	"Explode Balloon Probability" = 80.0
	#Probability that, after the balloon has exploded, different structures will be generated. The higher the number, the rarer it will be.
	"Balloon Structure Probability" = 2.0
	#Probability that the cross can be generated with 000. The higher the number, the rarer it will be.
	"000 Cross Probability" = 3.0
	#Probability that the cross can be generated without 000. The higher the number, the rarer it will be.
	"Normal Cross Probability" = 3.0
	"Game Crash?" = true
	"Enable Balloon Spawn?" = true

["Spawn Rate Balloon and 000 - Global"]
	#For each tick!
	"Minimum Ticks Spawn" = 36000.0
	#For each tick!
	"Maximum Ticks Spawn" = 64000.0
	"Enable 000 and 000 Hostile?" = true

["Eye Block"]
	#The higher the number, the rarer it will be to happen. When the player opens or closes the door, there is a chance that an Eye Block will appear.
	"Probability Eye Block Spawn" = 100.0
	#When the player touch the eye block.... (Disable if you have a basement in your house)
	"Enable Eye Block Touch?" = true
	#The larger the number, the less likely it is. Maze spawn chance when touching block
	"Max Spawn Maze Probability" = 30.0
	"Enable Eye Block?" = true

[Maze]
	"Enable Fog" = true
	"Enable Effects" = true
	#Activate the default maze that the mod brings when it is generated
	"Enable Maze by default" = true
	#If you have a house with a basement or stairs and you do not want the Bedrock to get in the way but you do want the maze to be generated, you can choose the maze adapted with obsidian to destroy the blocks
	"Enable Adaptive Maze" = false
	"Enable Maze Spawn?" = true
	Blindness = true
	Darkness = true
	Slowness = true

["Glass and Chat"]
	#This option is to enable or disable the glass cage that 000 and the spawning Villager cause, as well as the chat flood.
	"Glass 000 and Villager" = true
	#This disable Chat Flood when Eye Entity Spawns
	"Chat Flood Eye Entity" = true

